import Head from 'next/head'
import ListPokemons from '../components/ListPokemons'
import { getPokemons } from '../services/poke_api'
import { usePokemons } from '../hooks/usePokemons'
import { useRef } from 'react'
import { useIntersectedView } from '../hooks/useIntersectorView'
// import styles from '../styles/Home.module.css'

//#1B2631

export async function getServerSideProps(){
    
  const pokemons = await getPokemons({ url: 'https://pokeapi.co/api/v2/pokemon?limit=50?offset=0' })

  return {
      props: {
          pokemonsSSR : pokemons.results,
          nextRoute: pokemons.next
      }
  }
}

export default function Home({pokemonsSSR, nextRoute}) {

  const observerView = useRef()

  const [isVisible] = useIntersectedView(observerView, {
    rootMargin: '500px'
  })

  const { pokemons, loading, error } = usePokemons({initialState: pokemonsSSR, intersectionObserver: isVisible, nextRoute: nextRoute})

  return (
    <div className='w-full min-h-screen pb-20'>
      <Head>
        <title>Create Next App</title>
        <meta name='description" content="Generated by create next app' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='max-w-7xl m-auto'>
        <div className="text-center mt-10">
          <h1 className='text-4xl font-bold'>Bienvenido a la PokéApi</h1>
          <p className='my-4 font-semibold'>
            Esta es una aplicación que consume la PokéApi, una API que contiene información de los pokemones.
          </p>
        </div>

        <ListPokemons pokemons={pokemons}/>

        <div ref={observerView} className="w-full bg-black text-white">
          { loading && <p className="text-center py-4">Cargando...</p> }
          { error && <p className="text-center py-4">Error...</p> }
        </div>

        {/* <div className='w-full grid'>
          {loading && <p className='text-center'>Cargando...</p>}
          {error && <p className='text-center'>Ha ocurrido un error</p>}
          {pokemons.map(pokemon => (
            <div key={pokemon.name} className='bg-white rounded-lg shadow-lg p-4 m-4'>
              <p className='text-center text-xl font-bold'>{pokemon.name}</p>

              <div className='flex justify-center'>
                <img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${pokemon.url.split('/')[6]}.png`} alt={pokemon.name} />
              </div>
            </div>
          ))}
        </div> */}

      </div>
      
    </div>
  )
}
